version: '3.4'

services:
  productsdb:
    image: mongo:4.2

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products.API/Dockerfile

volumes:
  mongo_data:  