version: '3.4'

services:
  productsdb:
    container_name: productsdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  products.api:
    container_name: products.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productsdb:27017"
      - "MessageBroker:ConnectionString=host=rabbitmq"
    depends_on:
      - productsdb
      - rabbitmq
    ports:
      - "8000:80"

  deliveggie.gateway:
    container_name: deliveggie.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MessageBroker:ConnectionString=host=rabbitmq"
    depends_on:
      - rabbitmq
    ports:
      - "8001:80"
